version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
        name: install
        command: |
          sudo npm install -g yarn
          yarn install
      - run: yarn test
      - run: yarn semantic-release
